import { defineComponent, h, type Component, type PropType } from 'vue';

/**
 * Semantic adapter for coolicons v4.1.
 *
 * Existing feature code still emits MDI/Lucide names in a number of dynamic
 * data structures. Keeping that translation here gives the whole product one
 * icon language without coupling business components to font codepoints.
 */
const exactAliases: Record<string, string> = {
  // Core actions and navigation
  'mdi-plus': 'Add_Plus',
  'mdi-plus-circle-outline': 'Add_Plus_Circle',
  'mdi-minus': 'Remove_Minus',
  'mdi-close': 'Close_MD',
  'mdi-close-circle': 'Close_Circle',
  'mdi-check': 'Check',
  'mdi-check-all': 'Check_All',
  'mdi-check-circle': 'Circle_Check',
  'mdi-check-circle-outline': 'Circle_Check',
  'mdi-check-decagram': 'Wavy_Check',
  'mdi-arrow-left': 'Arrow_Left_MD',
  'mdi-arrow-left-bold': 'Arrow_Left_LG',
  'mdi-arrow-right': 'Arrow_Right_MD',
  'mdi-arrow-up': 'Arrow_Up_MD',
  'mdi-arrow-down': 'Arrow_Down_MD',
  'mdi-chevron-left': 'Chevron_Left',
  'mdi-chevron-right': 'Chevron_Right',
  'mdi-chevron-up': 'Chevron_Up',
  'mdi-chevron-down': 'Chevron_Down',
  'mdi-chevron-double-left': 'Chevron_Left_Duo',
  'mdi-chevron-double-right': 'Chevron_Right_Duo',
  'mdi-unfold-more-horizontal': 'Arrow_Left_Right',
  'mdi-dots-vertical': 'More_Vertical',
  'mdi-refresh': 'Arrows_Reload_01',
  'mdi-autorenew': 'Arrows_Reload_01',
  'mdi-sync': 'Arrows_Reload_01',
  'mdi-backup-restore': 'Arrow_Reload_02',
  'mdi-restore': 'Arrow_Undo_Down_Left',
  'mdi-undo': 'Undo',
  'mdi-reply': 'Forward',
  'mdi-loading': 'Loading',
  'mdi-download': 'Download',
  'mdi-upload': 'File_Upload',
  'mdi-open-in-new': 'External_Link',
  'mdi-content-copy': 'Copy',
  'mdi-content-save-outline': 'Save',
  'mdi-pencil': 'Edit_Pencil_01',
  'mdi-pencil-outline': 'Edit_Pencil_01',
  'mdi-delete': 'Trash_Empty',
  'mdi-delete-outline': 'Trash_Empty',
  'mdi-delete-forever': 'Trash_Full',
  'mdi-trash-can-outline': 'Trash_Empty',
  'mdi-filter-outline': 'Filter',
  'mdi-filter-variant': 'Filter',
  'mdi-magnify': 'Search_Magnifying_Glass',
  'mdi-magnify-scan': 'Search_Magnifying_Glass',
  'mdi-eye': 'Show',
  'mdi-eye-outline': 'Show',
  'mdi-eye-off': 'Hide',
  'mdi-eye-off-outline': 'Hide',
  'mdi-lock': 'Lock',
  'mdi-lock-outline': 'Lock',
  'mdi-lock-reset': 'Lock_Open',
  'mdi-login': 'Exit',
  'mdi-logout': 'Log_Out',
  'mdi-exit-to-app': 'Log_Out',
  'mdi-block-helper': 'Stop_Sign',
  'mdi-gesture-tap': 'Mouse',

  // People and organizations
  'mdi-account': 'User_01',
  'mdi-account-outline': 'User_01',
  'mdi-account-box-outline': 'User_Square',
  'mdi-account-circle': 'User_Circle',
  'mdi-account-circle-outline': 'User_Circle',
  'mdi-account-details': 'User_Card_ID',
  'mdi-account-plus': 'User_Add',
  'mdi-account-plus-outline': 'User_Add',
  'mdi-account-remove': 'User_Remove',
  'mdi-account-remove-outline': 'User_Remove',
  'mdi-account-off': 'User_Close',
  'mdi-account-off-outline': 'User_Close',
  'mdi-account-check': 'User_Check',
  'mdi-account-check-outline': 'User_Check',
  'mdi-account-clock-outline': 'User_03',
  'mdi-account-question': 'User_03',
  'mdi-account-search': 'User_Card_ID',
  'mdi-account-search-outline': 'User_Card_ID',
  'mdi-account-lock-outline': 'Lock',
  'mdi-account-tie': 'User_02',
  'mdi-account-tie-outline': 'User_02',
  'mdi-account-group': 'Users_Group',
  'mdi-account-group-outline': 'Users_Group',
  'mdi-account-multiple': 'Users',
  'mdi-account-multiple-outline': 'Users',
  'mdi-account-multiple-check': 'User_Check',
  'mdi-account-multiple-check-outline': 'User_Check',
  'mdi-folder-account-outline': 'Folder',
  'mdi-shield-account': 'User_Card_ID',
  'mdi-shield-account-outline': 'User_Card_ID',
  'mdi-table-account': 'Table',
  'mdi-target-account': 'User_Check',
  'mdi-human-male-female': 'Users',
  'mdi-gender-male': 'User_01',
  'mdi-gender-female': 'User_03',
  'mdi-domain': 'Building_02',
  'mdi-office-building': 'Building_01',
  'mdi-office-building-outline': 'Building_01',
  'mdi-home-city-outline': 'Building_04',

  // Communication
  'mdi-chat': 'Chat',
  'mdi-chat-outline': 'Chat',
  'mdi-chat-alert': 'Chat_Circle_Dots',
  'mdi-message-text': 'Chat_Conversation',
  'mdi-message-text-outline': 'Chat_Conversation',
  'mdi-message-outline': 'Chat',
  'mdi-message-plus': 'Chat_Add',
  'mdi-message-flash-outline': 'Chat_Dots',
  'mdi-message-arrow-left': 'Chat_Conversation',
  'mdi-message-arrow-left-outline': 'Chat_Conversation',
  'mdi-message-arrow-right': 'Paper_Plane',
  'mdi-message-arrow-right-outline': 'Paper_Plane',
  'mdi-send': 'Paper_Plane',
  'mdi-send-clock-outline': 'Paper_Plane',
  'mdi-email': 'Mail',
  'mdi-email-outline': 'Mail',
  'mdi-phone': 'Phone',
  'mdi-phone-outline': 'Phone',
  'mdi-phone-incoming': 'Phone',
  'mdi-phone-outgoing': 'Phone',
  'mdi-phone-missed': 'Phone',
  'mdi-phone-off': 'Phone',
  'mdi-phone-find-outline': 'Phone',
  'mdi-microphone': 'User_Voice',
  'mdi-bullhorn-outline': 'Volume_Max',
  'mdi-bullhorn-variant-outline': 'Volume_Max',
  'mdi-share': 'Share_Android',
  'mdi-share-variant': 'Share_Android',
  'mdi-link-variant': 'Link',
  'mdi-link-variant-plus': 'Link',
  'mdi-link-off': 'Link_Break',
  'mdi-link-variant-off': 'Link_Break',
  'mdi-connection': 'Link_Horizontal',
  'mdi-facebook': 'Globe',

  // Calendar and time
  'mdi-calendar': 'Calendar',
  'mdi-calendar-outline': 'Calendar',
  'mdi-calendar-today': 'Calendar_Days',
  'mdi-calendar-plus': 'Calendar_Add',
  'mdi-calendar-check-outline': 'Calendar_Check',
  'mdi-calendar-clock': 'Calendar_Event',
  'mdi-calendar-clock-outline': 'Calendar_Event',
  'mdi-calendar-start': 'Calendar_Days',
  'mdi-calendar-end': 'Calendar_Days',
  'mdi-calendar-heart': 'Calendar_Event',
  'mdi-clock-outline': 'Clock',
  'mdi-clock-check-outline': 'Clock',
  'mdi-clock-time-four-outline': 'Clock',
  'mdi-progress-clock': 'Timer',
  'mdi-timer-outline': 'Timer',
  'mdi-timer-sand': 'Timer',
  'mdi-history': 'Arrow_Undo_Down_Left',

  // Files and content
  'mdi-file-outline': 'File_Blank',
  'mdi-file-document-outline': 'File_Document',
  'mdi-file-excel': 'Table',
  'mdi-file-excel-outline': 'Table',
  'mdi-google-spreadsheet': 'Table',
  'mdi-file-tree-outline': 'Folders',
  'mdi-file-upload-outline': 'File_Upload',
  'mdi-archive': 'Archive',
  'mdi-archive-outline': 'Archive',
  'mdi-archive-arrow-up-outline': 'Folder_Upload',
  'mdi-folder-outline': 'Folder',
  'mdi-folder-open-outline': 'Folder_Open',
  'mdi-clipboard-text-outline': 'List_Checklist',
  'mdi-note-text-outline': 'Note',
  'mdi-note-edit-outline': 'Note_Edit',
  'mdi-bookmark': 'Bookmark',
  'mdi-bookmark-outline': 'Bookmark',
  'mdi-label-outline': 'Label',
  'mdi-tag-multiple-outline': 'Tag',
  'mdi-tag-off-outline': 'Label',
  'mdi-paperclip': 'Paperclip_Attechment_Tilt',
  'mdi-image': 'Image_01',
  'mdi-image-outline': 'Image_01',
  'mdi-image-multiple-outline': 'Image_02',
  'mdi-cloud-upload-outline': 'Cloud_Upload',
  'mdi-cloud-download-outline': 'Cloud_Download',

  // Data and product UI
  'mdi-chart-bar': 'Chart_Bar_Vertical_01',
  'mdi-chart-line': 'Chart_Line',
  'mdi-chart-donut': 'Chart_Pie',
  'mdi-chart-scatter-plot': 'Chart_Line',
  'mdi-chart-timeline-variant': 'Chart_Line',
  'mdi-chart-timeline-variant-shimmer': 'Chart_Line',
  'mdi-poll': 'Chart_Bar_Vertical_01',
  'mdi-trending-up': 'Trending_Up',
  'mdi-trending-down': 'Trending_Down',
  'mdi-view-dashboard-outline': 'More_Grid_Big',
  'mdi-view-grid-outline': 'More_Grid_Big',
  'mdi-view-list': 'List_Unordered',
  'mdi-view-column': 'Columns',
  'mdi-view-column-outline': 'Columns',
  'mdi-table': 'Table',
  'mdi-format-list-bulleted': 'List_Unordered',
  'mdi-format-list-checks': 'List_Checklist',
  'mdi-source-branch': 'Path',
  'mdi-merge': 'Combine_Cells',
  'mdi-swap-horizontal': 'Arrow_Left_Right',
  'mdi-compare-horizontal': 'Arrow_Left_Right',
  'mdi-counter': 'Data',
  'mdi-gauge': 'Chart_Pie',
  'mdi-pulse': 'Chart_Line',
  'mdi-monitor': 'Monitor',
  'mdi-monitor-dashboard': 'Window',
  'mdi-cellphone': 'Mobile',
  'mdi-cellphone-check': 'Mobile_Button',
  'mdi-cellphone-link': 'Devices',
  'mdi-cellphone-link-off': 'Devices',
  'mdi-cellphone-off': 'Mobile',
  'mdi-cellphone-remove': 'Mobile',
  'mdi-api': 'Code',
  'mdi-cursor-text': 'Text',
  'mdi-shape-outline': 'Layer',
  'mdi-puzzle-outline': 'Puzzle',
  'mdi-crane': 'Moving_Desk',

  // Status and feedback
  'mdi-alert': 'Warning',
  'mdi-alert-outline': 'Warning',
  'mdi-alert-circle': 'Circle_Warning',
  'mdi-alert-circle-outline': 'Circle_Warning',
  'mdi-information': 'Info',
  'mdi-information-outline': 'Info',
  'mdi-help-circle-outline': 'Circle_Help',
  'mdi-checkbox-marked': 'Checkbox_Check',
  'mdi-checkbox-blank-outline': 'Checkbox_Unchecked',
  'mdi-checkbox-blank-circle': 'Radio_Unchecked',
  'mdi-radiobox-marked': 'Radio_Fill',
  'mdi-radiobox-blank': 'Radio_Unchecked',
  'mdi-circle': 'Circle',
  'mdi-circle-medium': 'Dummy_Circle_Small',
  'mdi-circle-small': 'Dummy_Circle_Small',
  'mdi-circle-off-outline': 'Circle',
  'mdi-flag': 'Flag',
  'mdi-flag-outline': 'Flag',
  'mdi-flag-checkered': 'Flag',
  'mdi-bell-outline': 'Bell',
  'mdi-bell-ring': 'Bell_Ring',
  'mdi-bell-ring-outline': 'Bell_Ring',
  'mdi-bell-off-outline': 'Bell_Off',
  'mdi-bell-cog-outline': 'Bell_Notification',
  'mdi-shield-check-outline': 'Shield_Check',
  'mdi-shield-alert-outline': 'Shield_Warning',
  'mdi-shield-lock-outline': 'Shield',
  'mdi-shield-off': 'Shield_Warning',
  'mdi-star': 'Star',
  'mdi-star-outline': 'Star',
  'mdi-heart-outline': 'Heart_01',
  'mdi-heart-pulse': 'Heart_02',
  'mdi-lightbulb-on-outline': 'Bulb',
  'mdi-flash': 'Wavy',
  'mdi-lightning-bolt': 'Wavy',
  'mdi-fire': 'Trending_Up',
  'mdi-snowflake': 'Water_Drop',
  'mdi-snowflake-alert': 'Wavy_Warning',
  'mdi-emoticon-outline': 'User_Circle',
  'mdi-emoticon-happy-outline': 'Wavy_Check',
  'mdi-emoticon-neutral-outline': 'Wavy',
  'mdi-emoticon-sad-outline': 'Wavy_Warning',

  // Media and miscellaneous
  'mdi-play': 'Play',
  'mdi-play-circle': 'Play_Circle',
  'mdi-play-circle-outline': 'Play_Circle',
  'mdi-pause': 'Pause',
  'mdi-pause-circle': 'Pause_Circle',
  'mdi-stop': 'Stop',
  'mdi-skip-next': 'Skip_Forward',
  'mdi-video': 'Monitor_Play',
  'mdi-video-outline': 'Monitor_Play',
  'mdi-video-off': 'Monitor',
  'mdi-music-note': 'Volume_Min',
  'mdi-qrcode': 'Qr_Code',
  'mdi-qrcode-scan': 'Qr_Code',
  'mdi-web': 'Globe',
  'mdi-map-marker': 'Map_Pin',
  'mdi-map-marker-outline': 'Map_Pin',
  'mdi-home-outline': 'House_01',
  'mdi-home-map-marker': 'House_03',
  'mdi-weather-sunny': 'Sun',
  'mdi-weather-night': 'Moon',
  'mdi-weather-partly-cloudy': 'Cloud',
  'mdi-weather-sunset': 'Sun',
  'mdi-wifi-off': 'Wifi_Off',
  'mdi-coffee-outline': 'Coffee',
  'mdi-cake-variant': 'Cupcake',
  'mdi-gift-outline': 'Gift',
  'mdi-briefcase-outline': 'Suitcase',
  'mdi-briefcase-check': 'Suitcase',
  'mdi-cash': 'Credit_Card_01',
  'mdi-bank-transfer': 'Credit_Card_02',
  'mdi-handshake': 'User_Check',
  'mdi-medal-outline': 'Star',
  'mdi-trophy': 'Star',
  'mdi-trophy-outline': 'Star',
  'mdi-crown-outline': 'Star',
  'mdi-target': 'Compass',
  'mdi-identifier': 'User_Card_ID',
  'mdi-key-remove': 'Lock_Open',
  'mdi-scale-balance': 'Chart_Bar_Vertical_01',
  'mdi-brain': 'Bulb',
  'mdi-robot': 'Settings_Future',
  'mdi-robot-outline': 'Settings_Future',
  'mdi-settings': 'Settings',
  'mdi-cog-outline': 'Settings',
  'mdi-cog-sync-outline': 'Settings_Future',
  'mdi-tray-full': 'Archive',
};

const lucideAliases: Record<string, string> = {
  Activity: 'Chart_Line', AlertTriangle: 'Triangle_Warning', ArrowDownLeft: 'Arrow_Down_Left_MD',
  ArrowUpDown: 'Arrow_Down_Up', ArrowUpRight: 'Arrow_Up_Right_MD', Ban: 'Stop_Sign',
  BarChart3: 'Chart_Bar_Vertical_01', Bell: 'Bell', Bold: 'Bold', Bookmark: 'Bookmark',
  Bot: 'Settings_Future', Boxes: 'Layers', Briefcase: 'Suitcase', Cake: 'Cupcake',
  Calendar: 'Calendar', CalendarClock: 'Calendar_Event', CalendarDays: 'Calendar_Days',
  ChartColumn: 'Chart_Bar_Vertical_01', ChartNoAxesCombined: 'Chart_Line', Check: 'Check',
  CheckSquare: 'Checkbox_Check', ChevronDown: 'Chevron_Down', ChevronLeft: 'Chevron_Left',
  ChevronRight: 'Chevron_Right', ChevronUp: 'Chevron_Up', ChevronsLeft: 'Chevron_Left_Duo',
  ChevronsRight: 'Chevron_Right_Duo', Circle: 'Circle', CircleCheck: 'Circle_Check',
  ClipboardList: 'List_Checklist', Clock: 'Clock', Code: 'Code', Contact: 'User_Card_ID',
  ContactRound: 'User_Card_ID', Download: 'Download', Eye: 'Show', EyeOff: 'Hide',
  FileText: 'File_Document', Filter: 'Filter', Flag: 'Flag', Flame: 'Trending_Up',
  Folder: 'Folder', FolderTree: 'Folders', Gauge: 'Chart_Pie', Gift: 'Gift', Globe: 'Globe',
  Hand: 'Mouse', Image: 'Image_01', Images: 'Image_02', Inbox: 'Archive', Info: 'Info',
  Italic: 'Italic', LayoutDashboard: 'More_Grid_Big', Lightbulb: 'Bulb', List: 'List_Unordered',
  ListOrdered: 'List_Ordered', ListTodo: 'List_Checklist', Lock: 'Lock', LockKeyhole: 'Lock',
  MailCheck: 'Mail_Open', MailQuestion: 'Mail', Megaphone: 'Volume_Max', Menu: 'Hamburger_MD',
  MessageCircle: 'Chat_Circle', MessageSquareText: 'Chat_Conversation', Moon: 'Moon',
  MoreHorizontal: 'More_Horizontal', MoreVertical: 'More_Vertical', Package: 'Download_Package',
  PanelLeftClose: 'Bar_Left', PanelLeftOpen: 'Window_Sidebar', Paperclip: 'Paperclip_Attechment_Tilt',
  Pencil: 'Edit_Pencil_01', Phone: 'Phone', Play: 'Play', RefreshCw: 'Arrows_Reload_01',
  RotateCcw: 'Arrow_Reload_02', Search: 'Search_Magnifying_Glass', Send: 'Paper_Plane',
  Settings: 'Settings', Settings2: 'Slider_02', Shield: 'Shield', Smartphone: 'Mobile',
  Smile: 'User_Circle', Sparkles: 'Wavy', Star: 'Star', StickyNote: 'Note',
  Strikethrough: 'Strikethrough', Sun: 'Sun', Tag: 'Tag', Target: 'Compass', Trash2: 'Trash_Empty',
  TrendingUp: 'Trending_Up', TriangleAlert: 'Triangle_Warning', Trophy: 'Star', Type: 'Text', Underline: 'Underline',
  Undo2: 'Undo', Upload: 'File_Upload', User: 'User_01', UserCheck: 'User_Check',
  UserCircle: 'User_Circle', UserPlus: 'User_Add', UserRound: 'User_01', UserRoundCog: 'User_02',
  Users: 'Users', UsersRound: 'Users_Group', UserX: 'User_Remove', Video: 'Monitor_Play', X: 'Close_MD',
  Zap: 'Wavy',
};

const legacySymbolAliases: Record<string, string> = {
  '🔍': 'Search_Magnifying_Glass', '🔒': 'Lock', '🔓': 'Lock_Open',
  '✏': 'Edit_Pencil_01', '✏️': 'Edit_Pencil_01', '🗑': 'Trash_Empty', '🗑️': 'Trash_Empty',
  '📅': 'Calendar', '📞': 'Phone', '📧': 'Mail', '💬': 'Chat',
  '👤': 'User_01', '👥': 'Users_Group', '🤖': 'Settings_Future', '⭐': 'Star',
  '🎁': 'Gift', '🔥': 'Trending_Up', '📎': 'Paperclip_Attechment_Tilt',
  '📁': 'Folder', '📄': 'File_Document', '📊': 'Chart_Bar_Vertical_01',
  '🔔': 'Bell', '💡': 'Bulb', '🚀': 'Paper_Plane', '🎯': 'Compass',
  '📌': 'Map_Pin', '📝': 'Note_Edit', '🔗': 'Link', '⬇': 'Download', '⬇️': 'Download',
  '⬆': 'File_Upload', '⬆️': 'File_Upload', '▶': 'Play', '◀': 'Arrow_Left_MD',
  '➕': 'Add_Plus', '⚠': 'Warning', '⚠️': 'Warning', '✅': 'Check',
  '❌': 'Close_MD', '🌐': 'Globe', '⚡': 'Wavy', '📱': 'Mobile',
  '🔄': 'Arrows_Reload_01', '🤝': 'User_Check', '💌': 'Mail', '🏠': 'House_01',
  '📣': 'Volume_Max', '❄': 'Water_Drop', '❄️': 'Water_Drop', '🌊': 'Water_Drop',
  '📋': 'List_Checklist', '🎪': 'Ticket_Voucher', '🎵': 'Volume_Min', '☕': 'Coffee',
  '✕': 'Close_MD', '×': 'Close_MD', '✓': 'Check', '✔': 'Check', '⬜': 'Checkbox_Unchecked',
};

export function resolveCoolIcon(value: unknown): string {
  const raw = String(value ?? '').trim();
  if (!raw) return 'Circle_Help';
  if (raw.startsWith('ci-')) return raw.slice(3);
  if (lucideAliases[raw]) return lucideAliases[raw];
  if (legacySymbolAliases[raw]) return legacySymbolAliases[raw];

  const mdi = raw.match(/mdi-[a-z0-9-]+/)?.[0];
  if (mdi) {
    const exact = exactAliases[mdi];
    if (exact) return exact;
    if (mdi.includes('account') || mdi.includes('human')) return 'User_01';
    if (mdi.includes('calendar')) return 'Calendar';
    if (mdi.includes('message') || mdi.includes('chat')) return 'Chat';
    if (mdi.includes('file') || mdi.includes('document')) return 'File_Document';
    if (mdi.includes('folder')) return 'Folder';
    if (mdi.includes('alert') || mdi.includes('warning')) return 'Warning';
    if (mdi.includes('chart') || mdi.includes('analytics')) return 'Chart_Line';
    if (mdi.includes('settings') || mdi.includes('cog')) return 'Settings';
  }

  // Accept official coolicons names directly.
  if (/^[A-Z][A-Za-z0-9_]+$/.test(raw)) return raw;
  return 'Circle_Help';
}

export const CoolIcon = defineComponent({
  name: 'CoolIcon',
  inheritAttrs: false,
  props: {
    name: { type: [String, Object, Array] as PropType<unknown>, default: 'Circle_Help' },
    size: { type: [Number, String], default: 20 },
    color: { type: String, default: undefined },
    strokeWidth: { type: [Number, String], default: undefined },
  },
  setup(props, { attrs }) {
    return () => h('i', {
      ...attrs,
      class: ['cool-icon', `ci-${resolveCoolIcon(props.name)}`, attrs.class],
      style: [
        { fontSize: typeof props.size === 'number' ? `${props.size}px` : props.size, color: props.color },
        attrs.style,
      ],
      'aria-hidden': attrs['aria-label'] ? undefined : 'true',
    });
  },
});

export function createCoolIcon(name: string): Component {
  return defineComponent({
    name: `${name}CoolIcon`,
    inheritAttrs: false,
    props: {
      size: { type: [Number, String], default: 24 },
      color: { type: String, default: undefined },
      strokeWidth: { type: [Number, String], default: undefined },
      absoluteStrokeWidth: { type: Boolean, default: false },
    },
    setup(props, { attrs }) {
      return () => h(CoolIcon, { ...attrs, name, size: props.size, color: props.color });
    },
  });
}

export function createLucideCompatIcon(name: string): Component {
  return createCoolIcon(lucideAliases[name] ?? name);
}
